# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DING DONG
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Des artistes et des horloges en ville de Neuchâtel.
baseurl: "/ding_dong" # the subpath of your site, e.g. /blog
url: "www.dingdongneuchatel.ch" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Build settings
permalink: :title/
sass:
  sass_dir: css


defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
- jekyll-menus

